

from testing import makePlots_async


infile='<tree_association.txt file generated by the predict.py script>'

makePlots_async(infile,      #input file or file list
                ['test'],    #legend names (needs to be list)
                'reg_mttbar',    #variable to plot
                'reg_mttbar>600', #cut to apply
                'green',     #line color and style (e.g. 'red,dashed')
                'test.pdf',  #output file (pdf)
                'm_{t#bar{t}} [GeV]',     #xaxisname
                'events',     #yaxisname
                False)       #normalise